services:
  db:
    image: postgres:17-alpine
    container_name: digital-wallet-db
    environment:
      POSTGRES_USER: wallet_user
      POSTGRES_PASSWORD: wallet_pass
      POSTGRES_DB: digital_wallet
    ports:
      - "5440:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
